version: 2
jobs:
  build_master:
    environment:
      IMAGE_NAME : trendev/kiam-welcome
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: set $TAG
          command : TAG=$(echo $CIRCLE_SHA1 | cut -c1-8)
      - run:
          name: docker tag
          command: docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push $IMAGE_NAME:latest
          command: docker push $IMAGE_NAME:latest
      - run:
          name: docker push $IMAGE_NAME:$TAG
          command: docker push $IMAGE_NAME:$TAG
  # build: # generic job for other branches //should not be used for this project
  #   machine:
  #     image: ubuntu-1604:201903-01
  #     docker_layer_caching: true
  #   steps:
  #     - checkout
  #     - run:
  #         name: docker build
  #         # command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$CIRCLE_BRANCH -f $CIRCLE_BRANCH.Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
  #         command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$CIRCLE_BRANCH -f Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
  #     - run:
  #         name: docker login
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: docker push
  #         command: docker push $IMAGE_NAME:$CIRCLE_BRANCH
workflows:
  version: 2
  commit:
    jobs:
      - build_master:
          filters:
            branches:
              only: master
      # - build:
      #     filters:
      #       branches:
      #         only:
      #           - preprod
      #           # - preview
