version: 2
jobs:
  build_master:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $DOCKER_IMAGE:latest
  build: # generic job for other branches
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          # command: DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMAGE:$CIRCLE_BRANCH -f $CIRCLE_BRANCH.Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
          command: DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMAGE:$CIRCLE_BRANCH -f Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $DOCKER_IMAGE:$CIRCLE_BRANCH
workflows:
  version: 2
  commit:
    jobs:
      - build_master:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only:
                - preprod
                # - preview
